# Model Config: Llama-3.2-1B-Instruct
# This file now only contains model-specific information.
# The training profile is selected via the command line.

run_name: "llama_3_2_1b_qlora_webnlg_3_epochs_${now:%Y-%m-%d_%H-%M-%S}"

name: "unsloth/llama-3.2-1b-instruct-bnb-4bit"
name_sanitized: "llama-3-2-1b-instruct"
max_seq_length: 2048
dtype: null
load_in_4bit: true
