# Model Config: Llama-3.2-1B-Instruct
# This version now points to the 'strict' training configuration.

# This tells Hydra to load the main config, which then loads this model file.
# We are overriding the default training config with our new 'strict' one.
defaults:
  - override /training: strict

run_name: "llama_3_2_1b_strict_qlora_webnlg_3_epochs_${now:%Y-%m-%d_%H-%M-%S}"

name: "unsloth/llama-3.2-1b-instruct-bnb-4bit"
name_sanitized: "llama-3-2-1b-instruct"
max_seq_length: 2048
dtype: null
load_in_4bit: true
