# Model Config: Llama-3 8B (Default)

run_name: "llama3_8b_qlora_webnlg_3_epochs_${now:%Y-%m-%d_%H-%M-%S}"

name: "unsloth/llama-3-8b-Instruct-bnb-4bit"
name_sanitized: "llama-3-8b-instruct-bnb-4bit"
max_seq_length: 2048
dtype: null
load_in_4bit: true
