# Base Configuration for Graph2Text Finetuning (Offline Edition)

# FIX: Added a defaults list to correctly compose experiment configs.
# This tells Hydra to load this file first (_self_) and then load a file
# from the 'experiment' config group. The command-line argument will
# select WHICH file from that group to load.
defaults:
  - _self_
  - experiment: llama3_qlora_webnlg # This is the default if no experiment is specified

# --- Paths and Directories ---
output_dir: "outputs/${model.name_sanitized}/${run_name}"
run_name: "default_run_${now:%Y-%m-%d_%H-%M-%S}"

# --- Model Configuration ---
# NOTE: The 'model' block is now defined in each experiment file.
# This section is left here for reference but will be overridden.
model:
  name: "unsloth/llama-3-8b-Instruct-bnb-4bit"
  name_sanitized: "llama-3-8b-instruct-bnb-4bit"
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true

# --- Dataset and Dataloader ---
dataset:
  name: "web_nlg"
  subset: "webnlg_challenge_2017"
  text_col: "text"
  linearization_strategy: "simple_concise"

# --- Training Configuration ---
training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  num_train_epochs: 3
  learning_rate: 0.0001
  fp16: false
  bf16: true
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 42

# --- PEFT Configuration (LoRA / QLoRA) ---
peft:
  r: 16
  lora_alpha: 32
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: true
