# Base Configuration for Graph2Text Finetuning (Offline Edition)
# This file contains settings that are common across all experiments.
# It does NOT define a model. The model is defined in each experiment file.

# --- Paths and Directories ---
output_dir: "outputs/${model.name_sanitized}/${run_name}"
run_name: "default_run_${now:%Y-%m-%d_%H-%M-%S}"

# --- Dataset and Dataloader ---
dataset:
  name: "web_nlg"
  subset: "webnlg_challenge_2017"
  text_col: "text"
  linearization_strategy: "simple_concise"

# --- Training Configuration ---
training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  num_train_epochs: 3
  learning_rate: 0.0001
  fp16: false
  bf16: true
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 42

# --- PEFT Configuration (LoRA / QLoRA) ---
peft:
  r: 16
  lora_alpha: 32
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: true
